# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2305a82aee99ba0f2d02f42aae0c2eac2448f43b8dbc777de2f8894da467e83b4c88e7169da45759c82fe7f3e8f753b1edca14d47f48b6381ca734a0cfe7ad5

test:
  secret_key_base: 066b0de88bfb877c9eb76c7c8d6e382094181c9facce30a555cc88966757bb997b952051a674875ca56ab6789e23bc35ddfd3888cf5a785e87472f1367581284

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
